import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "../lib/api";
import { socket } from "../lib/socket";
import type { AdminPermission, AdminWalletTransaction, AuthUser, DepositRequest, MonthlyBonusRule, PlatformAuditItem, VipLevelRule, WithdrawalRequest } from "../types";
import { AdminContentStudio, type ContentItem } from "./AdminContentStudio";
import { NotificationRecipientPicker } from "./NotificationRecipientPicker";

type AdminTab = AdminPermission;
interface Props { onSignOut: () => void; currentUser: AuthUser; }
interface Summary { [key: string]: any; users: number; depositsPending: number; withdrawalsPending: number; activeBets: number; reconciliation: { balanced: boolean; difference: number; betEscrowMirrorDifference: number }; recentRounds: any[]; }
interface DailyBetReport { days: number; totals: any; rows: any[]; }
interface AdminSettings { houseEdgePercent: number; commissionPercent: number; reservePercent: number; minBet: number; minDeposit: number; minWithdrawal: number; wageringRequirementPercent: number; maxBet: number; maxCashoutMultiplier: number; depositsEnabled: boolean; withdrawalsEnabled: boolean; whatsappNumber?: string; whatsappMessage?: string; }
interface BonusClaim { id: string; userId: string | { _id: string; name: string; email: string }; type: "LEVEL_UP" | "MONTHLY"; amount: number; vipLevel: number; periodKey: string; createdAt: string; }
interface BonusData { config: { vipEnabled: boolean; vipLevelBonusEnabled: boolean; vipMonthlyBonusEnabled: boolean; vipWithdrawalLimitsEnabled: boolean; vipTimezone: string; monthlyClaimStartDay: number; monthlyClaimWindowHours: number; monthlyClaimForceOpen: boolean; vipLevels: VipLevelRule[]; monthlyBonusRules: MonthlyBonusRule[] }; budget: { bonusWallet: number; totalFunding: number; totalPaid: number }; claims: BonusClaim[]; }
interface Faq { _id: string; question: string; answer: string; category: string; enabled: boolean; sortOrder: number; }
interface Report { _id: string; userId: any; category: string; subject: string; description: string; status: string; adminNote?: string; createdAt: string; }
interface NotificationCampaign { _id: string; title: string; body: string; targetType: string; status: string; scheduledAt?: string; sentAt?: string; createdAt: string; }
interface SupportConversation { _id: string; userId: any; status: string; subject: string; unreadForAdmin: number; lastMessageAt: string; }
interface SupportMessage { id: string; senderId: any; senderRole: string; senderName?: string; message: string; createdAt: string | number; }
interface GameControl { planeOverrideEnabled: boolean; overrideCrashMultiplier: number; phase: string; multiplier: number; hasActiveBets: boolean; }

interface BonusDetailsProps {
  data: BonusData;
  busy: boolean;
  onChange: (config: BonusData["config"]) => void;
  onSave: () => void;
}

function BonusDetailSettings({ data, busy, onChange, onSave }: BonusDetailsProps) {
  const dateFormatter = new Intl.DateTimeFormat("en-CA", { timeZone: data.config.vipTimezone, year: "numeric", month: "2-digit", day: "2-digit" });
  const todayKey = dateFormatter.format(new Date());
  const todayClaims = data.claims.filter((claim) => dateFormatter.format(new Date(claim.createdAt)) === todayKey);
  const updateLevel = (index: number, key: keyof VipLevelRule, value: number) => {
    onChange({ ...data.config, vipLevels: data.config.vipLevels.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) });
  };
  const updateMonthly = (index: number, key: keyof MonthlyBonusRule, value: number) => {
    onChange({ ...data.config, monthlyBonusRules: data.config.monthlyBonusRules.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) });
  };
  const addMonthly = () => onChange({ ...data.config, monthlyBonusRules: [...data.config.monthlyBonusRules, { requiredDeposit: 0, requiredTurnover: 0, bonus: 0 }] });
  const removeMonthly = (index: number) => onChange({ ...data.config, monthlyBonusRules: data.config.monthlyBonusRules.filter((_, itemIndex) => itemIndex !== index) });

  return <form className="bonus-detail-settings" onSubmit={(event) => { event.preventDefault(); onSave(); }}>
    <div className="bonus-detail-heading"><div><span>Detailed configuration</span><h2>VIP levels & bonus rules</h2><p>These are the values used when users qualify for level-up, monthly and withdrawal-limit bonuses.</p></div><button className="save-settings" disabled={busy}>Save detailed settings</button></div>
    <section className="bonus-settings-section"><header><div><h3>VIP level rules</h3><p>Deposit and turnover requirements are cumulative. Use -1 for unlimited daily withdrawals.</p></div></header><div className="bonus-level-table"><div className="bonus-level-grid bonus-level-heading"><span>Level</span><span>Required deposit</span><span>Required turnover</span><span>Level-up bonus</span><span>Daily withdrawals</span></div>{data.config.vipLevels.map((item, index) => <div className="bonus-level-grid" key={item.level}><label><span className="mobile-only-label">Level</span><input type="number" value={item.level} readOnly /></label><label><span className="mobile-only-label">Required deposit</span><input type="number" min="0" value={item.requiredDeposit} onChange={(event) => updateLevel(index, "requiredDeposit", Number(event.target.value))} /></label><label><span className="mobile-only-label">Required turnover</span><input type="number" min="0" value={item.requiredTurnover} onChange={(event) => updateLevel(index, "requiredTurnover", Number(event.target.value))} /></label><label><span className="mobile-only-label">Level-up bonus</span><input type="number" min="0" value={item.levelUpBonus} onChange={(event) => updateLevel(index, "levelUpBonus", Number(event.target.value))} /></label><label><span className="mobile-only-label">Daily withdrawals</span><input type="number" min="-1" value={item.dailyWithdrawalLimit} onChange={(event) => updateLevel(index, "dailyWithdrawalLimit", Number(event.target.value))} /></label></div>)}</div></section>
    <section className="bonus-settings-section"><header><div><h3>Monthly bonus rules</h3><p>Each row is a qualification tier for the previous month.</p></div><button type="button" onClick={addMonthly}>Add tier</button></header><div className="monthly-bonus-list">{data.config.monthlyBonusRules.map((item, index) => <div className="monthly-bonus-row" key={`${index}-${item.requiredDeposit}-${item.requiredTurnover}`}><label>Required deposit<input type="number" min="0" value={item.requiredDeposit} onChange={(event) => updateMonthly(index, "requiredDeposit", Number(event.target.value))} /></label><label>Required turnover<input type="number" min="0" value={item.requiredTurnover} onChange={(event) => updateMonthly(index, "requiredTurnover", Number(event.target.value))} /></label><label>Bonus amount<input type="number" min="0" value={item.bonus} onChange={(event) => updateMonthly(index, "bonus", Number(event.target.value))} /></label><button type="button" className="danger" disabled={data.config.monthlyBonusRules.length <= 1} onClick={() => removeMonthly(index)}>Remove</button></div>)}</div></section>
    <section className="bonus-settings-section"><header><div><h3>Claim schedule</h3><p>Control when monthly claims open and which timezone is used.</p></div></header><div className="bonus-schedule-grid"><label>Timezone<select value={data.config.vipTimezone} onChange={(event) => onChange({ ...data.config, vipTimezone: event.target.value })}><option>Asia/Karachi</option><option>UTC</option><option>Asia/Dubai</option><option>Asia/Kolkata</option><option>Europe/London</option></select></label><label>Claim start day<input type="number" min="1" max="28" value={data.config.monthlyClaimStartDay} onChange={(event) => onChange({ ...data.config, monthlyClaimStartDay: Number(event.target.value) })} /></label><label>Claim window hours<input type="number" min="1" max="744" value={data.config.monthlyClaimWindowHours} onChange={(event) => onChange({ ...data.config, monthlyClaimWindowHours: Number(event.target.value) })} /></label><label className="toggle-setting"><input type="checkbox" checked={data.config.monthlyClaimForceOpen} onChange={(event) => onChange({ ...data.config, monthlyClaimForceOpen: event.target.checked })} /> Force monthly claim open</label></div></section>
    <section className="bonus-settings-section admin-reward-history"><header><div><h3>Daily rewards history</h3><p>Latest user bonus payouts, shown in {data.config.vipTimezone} time.</p></div><div className="reward-today-total"><span>Today</span><strong>{todayClaims.length} rewards · {money(todayClaims.reduce((total, claim) => total + claim.amount, 0))}</strong></div></header><div className="admin-table-card"><table><thead><tr><th>Date & time</th><th>User</th><th>Reward</th><th>Period / level</th><th>Amount</th></tr></thead><tbody>{data.claims.map((claim) => <tr key={claim.id}><td>{new Date(claim.createdAt).toLocaleString(undefined, { timeZone: data.config.vipTimezone })}</td><td>{person(claim.userId)}</td><td><span className="reward-type-badge">{claim.type === "LEVEL_UP" ? "Level up" : "Monthly"}</span></td><td>{claim.type === "LEVEL_UP" ? `VIP ${claim.vipLevel}` : claim.periodKey || "—"}</td><td><strong className="reward-amount">{money(claim.amount)}</strong></td></tr>)}{data.claims.length === 0 && <tr><td colSpan={5} className="empty-table-cell">No bonus rewards have been paid yet.</td></tr>}</tbody></table></div></section>
  </form>;
}

const ALL_TABS: Array<{ key: AdminTab; label: string }> = [
  { key: "OVERVIEW", label: "Dashboard" }, { key: "BETS", label: "Bets" }, { key: "BONUSES", label: "Bonuses" },
  { key: "USERS", label: "Users" }, { key: "DEPOSITS", label: "Deposits" }, { key: "WITHDRAWALS", label: "Withdrawals" },
  { key: "SUPPORT", label: "Live Support" }, { key: "CONTENT", label: "Banners & News" }, { key: "REPORTS", label: "Reports" },
  { key: "FAQS", label: "FAQs" }, { key: "NOTIFICATIONS", label: "Notifications" }, { key: "GAME_CONTROL", label: "Game Control" },
  { key: "TEAM", label: "Sub Admins" }, { key: "AUDIT", label: "Audit" }, { key: "SETTINGS", label: "Settings" }
];
const money = (value: number) => `${Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 })} PKR`;
const person = (value: any) => !value ? "System" : typeof value === "string" ? value : `${value.name} (${value.email})`;
const blankFaq = (): Omit<Faq, "_id"> => ({ question: "", answer: "", category: "General", enabled: true, sortOrder: 0 });

export function AdminPanel({ onSignOut, currentUser }: Props) {
  const allowedTabs = useMemo(() => currentUser.role === "ADMIN" ? ALL_TABS : ALL_TABS.filter((item) => currentUser.adminPermissions.includes(item.key)), [currentUser]);
  const [tab, setTab] = useState<AdminTab>(allowedTabs[0]?.key ?? "OVERVIEW");
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const [summary, setSummary] = useState<Summary | null>(null); const [betDays, setBetDays] = useState(30); const [betReport, setBetReport] = useState<DailyBetReport | null>(null);
  const [users, setUsers] = useState<AuthUser[]>([]); const [deposits, setDeposits] = useState<DepositRequest[]>([]); const [withdrawals, setWithdrawals] = useState<WithdrawalRequest[]>([]);
  const [dailyActiveUsers, setDailyActiveUsers] = useState(0);
  const [settings, setSettings] = useState<AdminSettings | null>(null); const [audit, setAudit] = useState<PlatformAuditItem[]>([]); const [transactions, setTransactions] = useState<AdminWalletTransaction[]>([]);
  const [auditQuery, setAuditQuery] = useState(""); const [auditType, setAuditType] = useState("ALL");
  const [bonusData, setBonusData] = useState<BonusData | null>(null); const [bonusFund, setBonusFund] = useState(10000); const [bonusLoading, setBonusLoading] = useState(false); const [bonusError, setBonusError] = useState("");
  const [content, setContent] = useState<ContentItem[]>([]);
  const [faqs, setFaqs] = useState<Faq[]>([]); const [faqForm, setFaqForm] = useState<any>(blankFaq()); const [editingFaq, setEditingFaq] = useState<string | null>(null);
  const [reports, setReports] = useState<Report[]>([]); const [reportStatus, setReportStatus] = useState("ALL");
  const [campaigns, setCampaigns] = useState<NotificationCampaign[]>([]); const [notificationForm, setNotificationForm] = useState({ title: "", body: "", targetType: "ALL", userIds: [] as string[], scheduledAt: "", sendNow: true });
  const [subadmins, setSubadmins] = useState<AuthUser[]>([]); const [permissions, setPermissions] = useState<AdminPermission[]>([]); const [subadminForm, setSubadminForm] = useState({ name: "", email: "", password: "", permissions: [] as AdminPermission[] });
  const [subadminPasswords, setSubadminPasswords] = useState<Record<string, string>>({});
  const [support, setSupport] = useState<SupportConversation[]>([]); const [selectedSupportUser, setSelectedSupportUser] = useState<string | null>(null); const [supportMessages, setSupportMessages] = useState<SupportMessage[]>([]); const [supportDraft, setSupportDraft] = useState("");
  const [gameControl, setGameControl] = useState<GameControl | null>(null);

  const run = async (action: () => Promise<void>, success = "Action completed successfully.") => { setBusy(true); setMessage(""); try { await action(); setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : "Action failed."); } finally { setBusy(false); } };
  const load = async (selected = tab) => {
    const routes: Partial<Record<AdminTab, () => Promise<void>>> = {
      OVERVIEW: async () => setSummary((await apiRequest<{ summary: Summary }>("/api/admin/summary")).summary),
      BETS: async () => setBetReport(await apiRequest<DailyBetReport>(`/api/admin/bets/daily?days=${betDays}`)),
      BONUSES: async () => { setBonusLoading(true); setBonusError(""); try { setBonusData(await apiRequest<BonusData>("/api/admin/bonuses")); } catch (error) { setBonusData(null); setBonusError(error instanceof Error ? error.message : "Unable to load bonus settings."); throw error; } finally { setBonusLoading(false); } },
      USERS: async () => { const result = await apiRequest<{ users: AuthUser[]; dailyActiveUsers: number }>("/api/admin/users"); setUsers(result.users); setDailyActiveUsers(result.dailyActiveUsers); },
      DEPOSITS: async () => setDeposits((await apiRequest<{ deposits: DepositRequest[] }>("/api/admin/deposits")).deposits),
      WITHDRAWALS: async () => setWithdrawals((await apiRequest<{ withdrawals: WithdrawalRequest[] }>("/api/admin/withdrawals")).withdrawals),
      AUDIT: async () => { const [a, t] = await Promise.all([apiRequest<{ audit: PlatformAuditItem[] }>("/api/admin/audit?limit=500"), apiRequest<{ transactions: AdminWalletTransaction[] }>("/api/admin/transactions?limit=500")]); setAudit(a.audit); setTransactions(t.transactions); },
      SETTINGS: async () => setSettings((await apiRequest<{ settings: AdminSettings }>("/api/admin/settings")).settings),
      CONTENT: async () => setContent((await apiRequest<{ items: ContentItem[] }>("/api/admin/content")).items),
      FAQS: async () => setFaqs((await apiRequest<{ faqs: Faq[] }>("/api/admin/faqs")).faqs),
      REPORTS: async () => setReports((await apiRequest<{ reports: Report[] }>(`/api/admin/reports?status=${reportStatus}`)).reports),
      NOTIFICATIONS: async () => {
        const result = await apiRequest<{ campaigns: NotificationCampaign[]; recipients: AuthUser[] }>("/api/admin/notifications");
        setCampaigns(result.campaigns);
        setUsers(result.recipients);
      },
      TEAM: async () => { const result = await apiRequest<{ users: AuthUser[]; permissions: AdminPermission[] }>("/api/admin/subadmins"); setSubadmins(result.users); setPermissions(result.permissions); },
      SUPPORT: async () => setSupport((await apiRequest<{ conversations: SupportConversation[] }>("/api/admin/support")).conversations),
      GAME_CONTROL: async () => setGameControl((await apiRequest<{ control: GameControl }>("/api/admin/game-control")).control)
    };
    await routes[selected]?.();
  };

  useEffect(() => { setMessage(""); void load().catch((error) => setMessage(error instanceof Error ? error.message : "Unable to load admin data.")); }, [tab, betDays, reportStatus]);
  useEffect(() => {
    const refresh = () => { if (tab === "SUPPORT") void load("SUPPORT"); };
    const onSupportMessage = (item: any) => {
      if (tab !== "SUPPORT") return;
      if (String(item.userId ?? "") === String(selectedSupportUser ?? "")) {
        setSupportMessages((messages) => messages.some((entry) => entry.id === String(item.id))
          ? messages
          : [...messages, {
              id: String(item.id), senderId: item.senderId, senderRole: item.senderRole,
              senderName: item.senderName, message: item.message, createdAt: item.createdAt
            }]);
      }
      void load("SUPPORT");
    };
    socket.on("support:updated", refresh);
    socket.on("support:new", onSupportMessage);
    return () => { socket.off("support:updated", refresh); socket.off("support:new", onSupportMessage); };
  }, [tab, selectedSupportUser]);

  const openSupport = (userId: string) => { setSelectedSupportUser(userId); socket.emit("support:load", { userId }, (result: any) => { if (!result.ok) { setMessage(result.message); return; } setSupportMessages((result.messages ?? []).map((item: any) => ({ id: String(item._id ?? item.id), senderId: item.senderId, senderRole: item.senderRole, senderName: typeof item.senderId === "object" ? item.senderId.name : undefined, message: item.message, createdAt: item.createdAt }))); }); };
  const sendSupport = () => { if (!selectedSupportUser || !supportDraft.trim()) return; const text = supportDraft.trim(); setSupportDraft(""); socket.emit("support:send", { userId: selectedSupportUser, message: text }, (result: any) => { if (!result.ok) setMessage(result.message); else openSupport(selectedSupportUser); }); };
  const selectedSupportConversation = useMemo(() => support.find((item) => String(item.userId?._id ?? item.userId) === String(selectedSupportUser ?? "")) ?? null, [support, selectedSupportUser]);

  const filteredAudit = useMemo(() => audit.filter((item) => (auditType === "ALL" || item.type === auditType) && `${item.type} ${item.description} ${person(item.userId)} ${item.roundId ?? ""} ${item.betId ?? ""}`.toLowerCase().includes(auditQuery.toLowerCase())), [audit, auditQuery, auditType]);
  const auditTypes = useMemo(() => Array.from(new Set(audit.map((item) => item.type))).sort(), [audit]);
  const overviewCards = summary ? [
    ["Users", summary.users, "USERS"], ["Pending deposits", summary.depositsPending, "DEPOSITS"], ["Open withdrawals", summary.withdrawalsPending, "WITHDRAWALS"], ["Active bets", summary.activeBets, "BETS"],
    ["Loss pool", money(summary.lossPool), "AUDIT"], ["Available reward liquidity", money(summary.availableRewardLiquidity), "BETS"], ["Reserved winner liquidity", money(summary.reservedRewardLiquidity), "BETS"], ["Active bet escrow", money(summary.activeBetEscrow), "BETS"],
    ["Commission wallet", money(summary.commissionWallet), "AUDIT"], ["VIP bonus wallet", money(summary.bonusWallet), "BONUSES"], ["Locked winnings", money(summary.pendingRewards), "USERS"], ["Wagering remaining", money(summary.totalWagerRequirement), "USERS"],
    ["Approved deposits", money(summary.totalApprovedDeposits), "DEPOSITS"], ["Completed withdrawals", money(summary.totalCompletedWithdrawals), "WITHDRAWALS"], ["Daily commission", money(summary.dailyRevenue), "AUDIT"], ["Monthly commission", money(summary.monthlyRevenue), "AUDIT"]
  ] as Array<[string, string | number, AdminTab]> : [];

  return <main className="admin-shell">
    <aside className="admin-sidebar"><div className="admin-title"><strong>B9T9 Admin</strong><span>{currentUser.role === "ADMIN" ? "Primary administrator" : "Restricted staff access"}</span></div>{allowedTabs.map((item) => <button className={tab === item.key ? "active" : ""} key={item.key} onClick={() => setTab(item.key)}>{item.label}</button>)}<button className="admin-signout" onClick={onSignOut}>Sign out</button></aside>
    <section className="admin-content"><header><div><h1>{ALL_TABS.find((item) => item.key === tab)?.label}</h1><p>Secure platform operations and user management.</p></div><button onClick={() => void load()}>Refresh</button></header>{message && <div className="admin-message">{message}</div>}

      {tab === "OVERVIEW" && summary && <><div className={`settings-warning ${summary.reconciliation.balanced ? "" : "danger"}`}>Accounting: <strong>{summary.reconciliation.balanced ? "BALANCED" : "REVIEW REQUIRED"}</strong>{` · Difference ${money(summary.reconciliation.difference)} · Escrow mirror ${money(summary.reconciliation.betEscrowMirrorDifference)}`}</div><div className="admin-kpis clickable-kpis">{overviewCards.filter(([, , target]) => currentUser.role === "ADMIN" || currentUser.adminPermissions.includes(target)).map(([label, value, target]) => <button key={label} onClick={() => setTab(target)}><span>{label}</span><strong>{value}</strong><small>Open {ALL_TABS.find((item) => item.key === target)?.label} →</small></button>)}</div><div className="admin-table-card"><h2>Recent rounds</h2><table><thead><tr><th>Round</th><th>Crash</th><th>Stake</th><th>Losses</th><th>Payout</th><th>Commission</th><th>Date</th></tr></thead><tbody>{summary.recentRounds.map((round) => <tr key={round._id}><td>{round.roundId.slice(0, 8)}</td><td>{Number(round.crashPoint).toFixed(2)}x</td><td>{money(round.totalStake)}</td><td>{money(round.totalLosses)}</td><td>{money(round.totalPayout)}</td><td>{money(round.totalCommission)}</td><td>{new Date(round.crashedAt).toLocaleString()}</td></tr>)}</tbody></table></div></>}

      {tab === "BETS" && betReport && <><div className="admin-report-toolbar"><div><h2>Daily bet report</h2><p>Review daily volume, user profit, losses and platform commission.</p></div><label>Range<select value={betDays} onChange={(event) => setBetDays(Number(event.target.value))}><option value={1}>Today / 1 day</option><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={365}>Last 365 days</option></select></label></div><div className="admin-kpis">{[["Total bets", betReport.totals.bets], ["Bet volume", money(betReport.totals.betVolume)], ["Player losses", money(betReport.totals.playerLoss)], ["Player profit", money(betReport.totals.playerProfit)], ["Commission", money(betReport.totals.commission)], ["Net game result", money(betReport.totals.netResult)]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="admin-table-card"><table><thead><tr><th>Date</th><th>Bets</th><th>Won / Lost / Open</th><th>Volume</th><th>Player loss</th><th>Player profit</th><th>Commission</th><th>Net result</th></tr></thead><tbody>{betReport.rows.map((row) => <tr key={row.date}><td>{new Date(`${row.date}T00:00:00+05:00`).toLocaleDateString()}</td><td>{row.bets}</td><td>{row.wonBets} / {row.lostBets} / {row.openBets}</td><td>{money(row.betVolume)}</td><td>{money(row.playerLoss)}</td><td>{money(row.playerProfit)}</td><td>{money(row.commission)}</td><td>{money(row.netResult)}</td></tr>)}</tbody></table></div></>}

      {tab === "BONUSES" && !bonusData && <div className="admin-state-card"><h2>{bonusLoading ? "Loading bonuses..." : "Bonus data unavailable"}</h2><p>{bonusLoading ? "Fetching the bonus wallet, VIP rules and claim history." : bonusError || "The bonus service did not return data."}</p>{!bonusLoading && <button onClick={() => void load("BONUSES")}>Retry</button>}</div>}
      {tab === "BONUSES" && bonusData && <><div className="admin-bonus-toolbar"><div><h2>VIP bonus budget</h2><p>Bonuses are paid from the dedicated bonus wallet.</p></div><label>Add funds<input type="number" value={bonusFund} onChange={(event) => setBonusFund(Number(event.target.value))} /></label><button disabled={busy} onClick={() => void run(async () => { await apiRequest("/api/admin/bonuses/fund", { method: "POST", body: JSON.stringify({ amount: bonusFund }) }); await load("BONUSES"); })}>Fund wallet</button></div><div className="admin-kpis"><article><span>Available</span><strong>{money(bonusData.budget.bonusWallet)}</strong></article><article><span>Total funded</span><strong>{money(bonusData.budget.totalFunding)}</strong></article><article><span>Total paid</span><strong>{money(bonusData.budget.totalPaid)}</strong></article><article><span>Claims</span><strong>{bonusData.claims.length}</strong></article></div><form className="admin-settings" onSubmit={(event) => { event.preventDefault(); void run(async () => { await apiRequest("/api/admin/bonuses/settings", { method: "PATCH", body: JSON.stringify(bonusData.config) }); await load("BONUSES"); }); }}><div className="settings-grid"><label className="toggle-setting"><input type="checkbox" checked={bonusData.config.vipEnabled} onChange={(event) => setBonusData({ ...bonusData, config: { ...bonusData.config, vipEnabled: event.target.checked } })} /> VIP enabled</label><label className="toggle-setting"><input type="checkbox" checked={bonusData.config.vipLevelBonusEnabled} onChange={(event) => setBonusData({ ...bonusData, config: { ...bonusData.config, vipLevelBonusEnabled: event.target.checked } })} /> Level-up bonuses</label><label className="toggle-setting"><input type="checkbox" checked={bonusData.config.vipMonthlyBonusEnabled} onChange={(event) => setBonusData({ ...bonusData, config: { ...bonusData.config, vipMonthlyBonusEnabled: event.target.checked } })} /> Monthly bonuses</label><label className="toggle-setting"><input type="checkbox" checked={bonusData.config.vipWithdrawalLimitsEnabled} onChange={(event) => setBonusData({ ...bonusData, config: { ...bonusData.config, vipWithdrawalLimitsEnabled: event.target.checked } })} /> VIP withdrawal limits</label></div><button className="save-settings" disabled={busy}>Save bonus settings</button></form></>}

      {tab === "USERS" && <><div className="admin-kpis admin-user-kpis"><article><span>Daily active users</span><strong>{dailyActiveUsers.toLocaleString()}</strong><small>Active today · Asia/Karachi</small></article></div><div className="admin-table-card"><table><thead><tr><th>User</th><th>Email</th><th>Available</th><th>Bet lock</th><th>Pending rewards</th><th>Wager remaining</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td>{user.name}</td><td>{user.email}</td><td>{money(user.balance)}</td><td>{money(user.bettingLockedBalance)}</td><td>{money(user.pendingRewards)}</td><td>{money(user.wagerRequirementRemaining)}</td><td>{user.status}</td><td>{user.role === "USER" && <button onClick={() => void run(async () => { await apiRequest(`/api/admin/users/${user.id}`, { method: "PATCH", body: JSON.stringify({ status: user.status === "ACTIVE" ? "SUSPENDED" : "ACTIVE" }) }); await load("USERS"); })}>{user.status === "ACTIVE" ? "Suspend" : "Activate"}</button>}</td></tr>)}</tbody></table></div></>}

      {tab === "DEPOSITS" && <div className="admin-table-card"><table><thead><tr><th>User</th><th>Amount</th><th>Method</th><th>Reference</th><th>Status</th><th>Actions</th></tr></thead><tbody>{deposits.map((item) => <tr key={item._id}><td>{person(item.userId)}</td><td>{money(item.amount)}</td><td>{item.method}</td><td>{item.reference}</td><td>{item.gatewayStatus ? `${item.status} · ${item.gatewayStatus.replaceAll("_", " ")}` : item.status}</td><td>{item.status === "PENDING" && (item.gatewayProvider ? <small>Automatic settlement</small> : <div className="admin-actions"><button onClick={() => void run(async () => { await apiRequest(`/api/admin/deposits/${item._id}`, { method: "PATCH", body: JSON.stringify({ action: "APPROVE" }) }); await load("DEPOSITS"); })}>Approve</button><button className="danger" onClick={() => void run(async () => { await apiRequest(`/api/admin/deposits/${item._id}`, { method: "PATCH", body: JSON.stringify({ action: "REJECT" }) }); await load("DEPOSITS"); })}>Reject</button></div>)}</td></tr>)}</tbody></table></div>}

      {tab === "WITHDRAWALS" && <div className="admin-table-card"><table><thead><tr><th>User</th><th>Amount</th><th>Method</th><th>Details</th><th>Status</th><th>Actions</th></tr></thead><tbody>{withdrawals.map((item) => <tr key={item._id}><td>{person(item.userId)}</td><td>{money(item.amount)}</td><td>{item.method}</td><td className="wrap-cell">{item.accountDetails}</td><td>{item.status}</td><td>{!["COMPLETED", "REJECTED"].includes(item.status) && <div className="admin-actions">{item.status === "PENDING" && <button onClick={() => void run(async () => { await apiRequest(`/api/admin/withdrawals/${item._id}`, { method: "PATCH", body: JSON.stringify({ action: "PROCESS" }) }); await load("WITHDRAWALS"); })}>Process</button>}<button onClick={() => void run(async () => { await apiRequest(`/api/admin/withdrawals/${item._id}`, { method: "PATCH", body: JSON.stringify({ action: "COMPLETE" }) }); await load("WITHDRAWALS"); })}>Complete</button><button className="danger" onClick={() => void run(async () => { await apiRequest(`/api/admin/withdrawals/${item._id}`, { method: "PATCH", body: JSON.stringify({ action: "REJECT" }) }); await load("WITHDRAWALS"); })}>Reject</button></div>}</td></tr>)}</tbody></table></div>}

      {tab === "SUPPORT" && <div className="admin-support-layout">
        <aside>{support.length === 0 ? <p>No support conversations.</p> : support.map((item) => <button className={selectedSupportUser === String(item.userId?._id ?? item.userId) ? "active" : ""} key={item._id} onClick={() => openSupport(String(item.userId?._id ?? item.userId))}><strong>{item.userId?.name ?? "User"}</strong><span>{item.subject}</span><small>{new Date(item.lastMessageAt).toLocaleString()}</small>{item.unreadForAdmin > 0 && <b>{item.unreadForAdmin}</b>}</button>)}</aside>
        <section>
          <header><div><h2>{selectedSupportConversation?.userId?.name ?? (selectedSupportUser ? "Support conversation" : "Select a user")}</h2>{selectedSupportConversation && <small>{selectedSupportConversation.status} · {selectedSupportConversation.subject}</small>}</div>{selectedSupportConversation && <button onClick={() => void run(async () => { await apiRequest(`/api/admin/support/${selectedSupportConversation._id}`, { method: "PATCH", body: JSON.stringify({ status: selectedSupportConversation.status === "OPEN" ? "CLOSED" : "OPEN" }) }); await load("SUPPORT"); }, selectedSupportConversation.status === "OPEN" ? "Conversation closed." : "Conversation reopened.")}>{selectedSupportConversation.status === "OPEN" ? "Close ticket" : "Reopen ticket"}</button>}</header>
          <div className="admin-support-messages">{supportMessages.map((item) => <article className={item.senderRole === "USER" ? "user" : "admin"} key={item.id}><small>{item.senderRole === "USER" ? "User" : item.senderName || "Admin"}</small><p>{item.message}</p><time>{new Date(item.createdAt).toLocaleString()}</time></article>)}</div>
          {selectedSupportUser && <footer><textarea value={supportDraft} onChange={(event) => setSupportDraft(event.target.value)} placeholder="Reply to user…" /><button onClick={sendSupport}>Send</button></footer>}
        </section>
      </div>}

      {tab === "CONTENT" && <AdminContentStudio items={content} run={run} onReload={() => load("CONTENT")} />}

      {tab === "REPORTS" && <><div className="admin-report-toolbar"><div><h2>User reports</h2><p>Account, payment, security and game issues submitted by users.</p></div><label>Status<select value={reportStatus} onChange={(event) => setReportStatus(event.target.value)}><option>ALL</option><option>OPEN</option><option>IN_REVIEW</option><option>RESOLVED</option><option>REJECTED</option></select></label></div><div className="admin-card-list reports-admin-list">{reports.map((item) => <article key={item._id}><div><span>{item.category} · {person(item.userId)}</span><h3>{item.subject}</h3><p>{item.description}</p><small>{new Date(item.createdAt).toLocaleString()}</small></div><div className="report-admin-actions"><select value={item.status} onChange={(event) => setReports((items) => items.map((entry) => entry._id === item._id ? { ...entry, status: event.target.value } : entry))}><option>OPEN</option><option>IN_REVIEW</option><option>RESOLVED</option><option>REJECTED</option></select><textarea value={item.adminNote ?? ""} placeholder="Admin note" onChange={(event) => setReports((items) => items.map((entry) => entry._id === item._id ? { ...entry, adminNote: event.target.value } : entry))} /><button onClick={() => void run(async () => { await apiRequest(`/api/admin/reports/${item._id}`, { method: "PATCH", body: JSON.stringify({ status: item.status, adminNote: item.adminNote }) }); await load("REPORTS"); })}>Save</button></div></article>)}</div></>}

      {tab === "FAQS" && <div className="admin-split-layout"><form className="admin-editor" onSubmit={(event) => { event.preventDefault(); void run(async () => { await apiRequest(editingFaq ? `/api/admin/faqs/${editingFaq}` : "/api/admin/faqs", { method: editingFaq ? "PATCH" : "POST", body: JSON.stringify(faqForm) }); setFaqForm(blankFaq()); setEditingFaq(null); await load("FAQS"); }); }}><h2>{editingFaq ? "Edit FAQ" : "Create FAQ"}</h2><label>Question<input required value={faqForm.question} onChange={(event) => setFaqForm({ ...faqForm, question: event.target.value })} /></label><label>Answer<textarea required value={faqForm.answer} onChange={(event) => setFaqForm({ ...faqForm, answer: event.target.value })} /></label><label>Category<input value={faqForm.category} onChange={(event) => setFaqForm({ ...faqForm, category: event.target.value })} /></label><label>Sort order<input type="number" value={faqForm.sortOrder} onChange={(event) => setFaqForm({ ...faqForm, sortOrder: Number(event.target.value) })} /></label><label className="toggle-setting"><input type="checkbox" checked={faqForm.enabled} onChange={(event) => setFaqForm({ ...faqForm, enabled: event.target.checked })} /> Enabled</label><button className="save-settings">Save FAQ</button></form><div className="admin-card-list">{faqs.map((item) => <article key={item._id}><div><span>{item.category}</span><h3>{item.question}</h3><p>{item.answer}</p><small>{item.enabled ? "Visible" : "Hidden"}</small></div><div><button onClick={() => { setEditingFaq(item._id); setFaqForm(item); }}>Edit</button><button className="danger" onClick={() => void run(async () => { await apiRequest(`/api/admin/faqs/${item._id}`, { method: "DELETE" }); await load("FAQS"); })}>Delete</button></div></article>)}</div></div>}

      {tab === "NOTIFICATIONS" && <div className="admin-split-layout"><form className="admin-editor" onSubmit={(event) => { event.preventDefault(); void run(async () => { await apiRequest("/api/admin/notifications", { method: "POST", body: JSON.stringify({ ...notificationForm, scheduledAt: !notificationForm.sendNow && notificationForm.scheduledAt ? new Date(notificationForm.scheduledAt).toISOString() : undefined }) }); setNotificationForm({ title: "", body: "", targetType: "ALL", userIds: [], scheduledAt: "", sendNow: true }); await load("NOTIFICATIONS"); }, notificationForm.sendNow ? "Notification sent." : "Notification scheduled."); }}><h2>Send notification</h2><label>Title<input required value={notificationForm.title} onChange={(event) => setNotificationForm({ ...notificationForm, title: event.target.value })} /></label><label>Message<textarea required value={notificationForm.body} onChange={(event) => setNotificationForm({ ...notificationForm, body: event.target.value })} /></label><label>Recipients<select value={notificationForm.targetType} onChange={(event) => setNotificationForm({ ...notificationForm, targetType: event.target.value })}><option value="ALL">All users</option><option value="SELECTED">Selected users</option></select></label>{notificationForm.targetType === "SELECTED" && <NotificationRecipientPicker users={users} value={notificationForm.userIds} onChange={(userIds) => setNotificationForm({ ...notificationForm, userIds })} />}<label className="toggle-setting"><input type="checkbox" checked={notificationForm.sendNow} onChange={(event) => setNotificationForm({ ...notificationForm, sendNow: event.target.checked })} /> Send immediately</label>{!notificationForm.sendNow && <label>Schedule time<input type="datetime-local" value={notificationForm.scheduledAt} onChange={(event) => setNotificationForm({ ...notificationForm, scheduledAt: event.target.value })} /></label>}<button className="save-settings">{notificationForm.sendNow ? "Send notification" : "Schedule notification"}</button></form><div className="admin-card-list">{campaigns.map((item) => <article key={item._id}><div><span>{item.targetType} · {item.status}</span><h3>{item.title}</h3><p>{item.body}</p><small>{item.sentAt ? `Sent ${new Date(item.sentAt).toLocaleString()}` : item.scheduledAt ? `Scheduled ${new Date(item.scheduledAt).toLocaleString()}` : new Date(item.createdAt).toLocaleString()}</small></div>{item.status === "SCHEDULED" && <button className="danger" onClick={() => void run(async () => { await apiRequest(`/api/admin/notifications/${item._id}/cancel`, { method: "PATCH" }); await load("NOTIFICATIONS"); })}>Cancel</button>}</article>)}</div></div>}

      {tab === "TEAM" && <div className="admin-split-layout">
        <form className="admin-editor" onSubmit={(event) => {
          event.preventDefault();
          void run(async () => {
            await apiRequest("/api/admin/subadmins", { method: "POST", body: JSON.stringify(subadminForm) });
            setSubadminForm({ name: "", email: "", password: "", permissions: [] });
            await load("TEAM");
          }, "Sub administrator created.");
        }}>
          <h2>Create sub admin</h2>
          <label>Name<input required value={subadminForm.name} onChange={(event) => setSubadminForm({ ...subadminForm, name: event.target.value })} /></label>
          <label>Email<input type="email" required value={subadminForm.email} onChange={(event) => setSubadminForm({ ...subadminForm, email: event.target.value })} /></label>
          <label>Temporary password<input type="password" minLength={10} required value={subadminForm.password} onChange={(event) => setSubadminForm({ ...subadminForm, password: event.target.value })} /></label>
          <fieldset className="permission-grid"><legend>Page access</legend>{permissions.map((permission) => <label key={permission}><input type="checkbox" checked={subadminForm.permissions.includes(permission)} onChange={(event) => setSubadminForm({ ...subadminForm, permissions: event.target.checked ? [...subadminForm.permissions, permission] : subadminForm.permissions.filter((item) => item !== permission) })} /> {permission.replaceAll("_", " ")}</label>)}</fieldset>
          <button className="save-settings">Create sub admin</button>
        </form>
        <div className="admin-card-list subadmin-list">{subadmins.map((item) => <article key={item.id}>
          <div className="subadmin-summary"><span>{item.status}</span><h3>{item.name}</h3><p>{item.email}</p><small>{item.adminPermissions.length} permitted page{item.adminPermissions.length === 1 ? "" : "s"}</small></div>
          <details className="subadmin-access">
            <summary>Manage access & security</summary>
            <fieldset className="permission-grid compact">{permissions.map((permission) => <label key={permission}><input type="checkbox" checked={item.adminPermissions.includes(permission)} onChange={(event) => setSubadmins((entries) => entries.map((entry) => entry.id === item.id ? { ...entry, adminPermissions: event.target.checked ? [...entry.adminPermissions, permission] : entry.adminPermissions.filter((value) => value !== permission) } : entry))} /> {permission.replaceAll("_", " ")}</label>)}</fieldset>
            <label className="subadmin-password">New password (optional)<input type="password" minLength={10} value={subadminPasswords[item.id] ?? ""} onChange={(event) => setSubadminPasswords((values) => ({ ...values, [item.id]: event.target.value }))} placeholder="At least 10 characters" /></label>
            <div className="admin-actions">
              <button onClick={() => void run(async () => { await apiRequest(`/api/admin/subadmins/${item.id}`, { method: "PATCH", body: JSON.stringify({ permissions: item.adminPermissions, password: subadminPasswords[item.id] || undefined }) }); setSubadminPasswords((values) => ({ ...values, [item.id]: "" })); await load("TEAM"); }, "Sub administrator access updated.")}>Save access</button>
              <button className={item.status === "ACTIVE" ? "danger" : ""} onClick={() => void run(async () => { await apiRequest(`/api/admin/subadmins/${item.id}`, { method: "PATCH", body: JSON.stringify({ status: item.status === "ACTIVE" ? "SUSPENDED" : "ACTIVE" }) }); await load("TEAM"); }, item.status === "ACTIVE" ? "Sub administrator suspended." : "Sub administrator activated.")}>{item.status === "ACTIVE" ? "Suspend" : "Activate"}</button>
            </div>
          </details>
        </article>)}</div>
      </div>}

      {tab === "GAME_CONTROL" && gameControl && <section className="game-control-card"><div className="game-control-status"><article><span>Override</span><strong>{gameControl.planeOverrideEnabled ? "ACTIVE" : "OFF"}</strong></article><article><span>Current phase</span><strong>{gameControl.phase}</strong></article><article><span>Current multiplier</span><strong>{gameControl.multiplier.toFixed(2)}x</strong></article><article><span>Active/queued bets</span><strong>{gameControl.hasActiveBets ? "Present" : "None"}</strong></article></div><label className="toggle-setting"><input type="checkbox" checked={gameControl.planeOverrideEnabled} onChange={(event) => setGameControl({ ...gameControl, planeOverrideEnabled: event.target.checked })} /> Enable plane override</label><label>Next crash multiplier<input type="number" min="1" max="1000" step="0.01" value={gameControl.overrideCrashMultiplier} onChange={(event) => setGameControl({ ...gameControl, overrideCrashMultiplier: Number(event.target.value) })} /></label><div className="admin-actions"><button onClick={() => void run(async () => { await apiRequest("/api/admin/game-control", { method: "PATCH", body: JSON.stringify({ enabled: gameControl.planeOverrideEnabled, crashMultiplier: gameControl.overrideCrashMultiplier }) }); await load("GAME_CONTROL"); })}>Save control</button><button className="danger" disabled={!gameControl.planeOverrideEnabled || gameControl.phase !== "RUNNING"} onClick={() => void run(async () => { await apiRequest("/api/admin/game-control", { method: "PATCH", body: JSON.stringify({ forceCrash: true }) }); await load("GAME_CONTROL"); })}>Stop current plane</button></div></section>}

      {tab === "AUDIT" && <><div className="audit-toolbar"><input value={auditQuery} onChange={(event) => setAuditQuery(event.target.value)} placeholder="Search user, event, round or description" /><select value={auditType} onChange={(event) => setAuditType(event.target.value)}><option value="ALL">All events</option>{auditTypes.map((type) => <option key={type}>{type}</option>)}</select><span>{filteredAudit.length} events</span></div><div className="audit-summary-grid"><article><span>Escrow movement</span><strong>{money(filteredAudit.reduce((sum, item) => sum + item.activeBetEscrowDelta, 0))}</strong></article><article><span>Reserve movement</span><strong>{money(filteredAudit.reduce((sum, item) => sum + item.reservedLiquidityDelta, 0))}</strong></article><article><span>Pool movement</span><strong>{money(filteredAudit.reduce((sum, item) => sum + item.lossPoolDelta, 0))}</strong></article><article><span>Commission movement</span><strong>{money(filteredAudit.reduce((sum, item) => sum + item.commissionWalletDelta, 0))}</strong></article></div><div className="admin-table-card audit-table"><table><thead><tr><th>Date</th><th>Event</th><th>User</th><th>Round / Bet</th><th>Escrow Δ</th><th>Reserve Δ</th><th>Pool Δ</th><th>Commission Δ</th><th>Description</th></tr></thead><tbody>{filteredAudit.map((item) => <tr key={item._id}><td>{new Date(item.createdAt).toLocaleString()}</td><td><span className="audit-event-badge">{item.type.replaceAll("_", " ")}</span></td><td>{person(item.userId)}</td><td>{item.roundId?.slice(0, 8) || "—"}<br/><small>{item.betId?.slice(0, 8) || ""}</small></td><td>{money(item.activeBetEscrowDelta)}</td><td>{money(item.reservedLiquidityDelta)}</td><td>{money(item.lossPoolDelta)}</td><td>{money(item.commissionWalletDelta)}</td><td className="wrap-cell">{item.description}</td></tr>)}</tbody></table></div><details className="wallet-ledger"><summary>User wallet ledger ({transactions.length})</summary><div className="admin-table-card"><table><thead><tr><th>Date</th><th>User</th><th>Type</th><th>Amount</th><th>Available after</th><th>Bet escrow</th><th>Description</th></tr></thead><tbody>{transactions.map((item) => <tr key={item._id}><td>{new Date(item.createdAt).toLocaleString()}</td><td>{person(item.userId)}</td><td>{item.type}</td><td>{money(item.amount)}</td><td>{money(item.balanceAfter)}</td><td>{money(item.bettingLockedAfter ?? 0)}</td><td>{item.description}</td></tr>)}</tbody></table></div></details></>}

      {tab === "SETTINGS" && settings && <form className="admin-settings" onSubmit={(event) => { event.preventDefault(); void run(async () => { await apiRequest("/api/admin/settings", { method: "PATCH", body: JSON.stringify(settings) }); await load("SETTINGS"); }); }}><div className="settings-grid"><label>House edge %<input type="number" value={settings.houseEdgePercent} onChange={(event) => setSettings({ ...settings, houseEdgePercent: Number(event.target.value) })} /></label><label>Commission %<input type="number" value={settings.commissionPercent} onChange={(event) => setSettings({ ...settings, commissionPercent: Number(event.target.value) })} /></label><label>Protected reserve %<input type="number" value={settings.reservePercent} onChange={(event) => setSettings({ ...settings, reservePercent: Number(event.target.value) })} /></label><label>Minimum bet<input type="number" value={settings.minBet} onChange={(event) => setSettings({ ...settings, minBet: Number(event.target.value) })} /></label><label>Maximum bet<input type="number" value={settings.maxBet} onChange={(event) => setSettings({ ...settings, maxBet: Number(event.target.value) })} /></label><label>Maximum cash-out<input type="number" value={settings.maxCashoutMultiplier} onChange={(event) => setSettings({ ...settings, maxCashoutMultiplier: Number(event.target.value) })} /></label><label>Minimum deposit<input type="number" value={settings.minDeposit} onChange={(event) => setSettings({ ...settings, minDeposit: Number(event.target.value) })} /></label><label>Minimum withdrawal<input type="number" value={settings.minWithdrawal} onChange={(event) => setSettings({ ...settings, minWithdrawal: Number(event.target.value) })} /></label><label>Wagering requirement %<input type="number" value={settings.wageringRequirementPercent} onChange={(event) => setSettings({ ...settings, wageringRequirementPercent: Number(event.target.value) })} /></label><label className="toggle-setting"><input type="checkbox" checked={settings.depositsEnabled} onChange={(event) => setSettings({ ...settings, depositsEnabled: event.target.checked })} /> Deposits enabled</label><label className="toggle-setting"><input type="checkbox" checked={settings.withdrawalsEnabled} onChange={(event) => setSettings({ ...settings, withdrawalsEnabled: event.target.checked })} /> Withdrawals enabled</label></div><button className="save-settings">Save settings</button></form>}
      {tab === "BONUSES" && bonusData && <BonusDetailSettings data={bonusData} busy={busy} onChange={(config) => setBonusData({ ...bonusData, config })} onSave={() => void run(async () => { await apiRequest("/api/admin/bonuses/settings", { method: "PATCH", body: JSON.stringify(bonusData.config) }); await load("BONUSES"); }, "Detailed bonus settings saved.")} />}
    </section>
  </main>;
}
